USE oncology_db;
CREATE TABLE IF NOT EXISTS medicines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(40) NOT NULL UNIQUE,
  product_name VARCHAR(220) NOT NULL,
  form VARCHAR(80) NULL,
  strength VARCHAR(120) NULL,
  source VARCHAR(120) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_medicines_product_name (product_name),
  INDEX idx_medicines_sku (sku)
);
INSERT INTO medicines (sku, product_name, form, strength, source) VALUES
  ('989', 'ALGIN 100ML SYRP 1X1''S', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('N53', 'ALGIN 50MG TABS 10X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('C62', 'ALGIN 50ML SYRP 1X1''S', 'Syrup', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('229', 'ALGIN 5MG INJ 2ML 1X5''S', 'Injection', '5MG, 2ML', 'Renata All SKU and BRANDS.xls'),
  ('007', 'ALPHAPRESS 1MG TAB (10X10''S)', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('008', 'ALPHAPRESS 2MG TAB (10X10''S)', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('C68', 'ALPHAPRESS XR 2.5MG 3X10''S', 'Medicine', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C69', 'ALPHAPRESS XR 5MG 3X10''S', 'Medicine', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('N5B', 'BISOREN 1.25MG TAB 3X10''S', 'Tablet', '1.25MG', 'Renata All SKU and BRANDS.xls'),
  ('983', 'BISOREN 2.5MG TAB (3X10''S)', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('984', 'BISOREN 5MG TAB (3X10''S)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('N2L', 'BISOREN FC 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C09', 'BISOREN PLUS FC 2.5MG TAB 3X10''S', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C08', 'BISOREN PLUS FC 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('S28', 'BISOREN-M 2.5MG TAB 3X10''S', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C27', 'CORALCIN-D TAB 6X10''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C5A', 'CORALCIN-DV FC TAB 1X30''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('N4M', 'CORALCIN-DX FC TAB 5X8''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('S92', 'CORALCIN-DX TAB 1X15''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('S93', 'CORALCIN-DX TAB 1X30''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('069', 'FENADIN 30ML SUSPENSION 1''S', 'Suspension', '30ML', 'Renata All SKU and BRANDS.xls'),
  ('291', 'FENADIN FC 120MG TAB 5X10''S', 'Tablet', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('185', 'FENADIN FC 180MG TAB (2X10''S)', 'Tablet', '180MG', 'Renata All SKU and BRANDS.xls'),
  ('188', 'FENADIN FC 60MG TAB 3X10''S', 'Tablet', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('C7B', 'FENADIN FC ODT 30MG TAB 3X10''S', 'Tablet', '30MG', 'Renata All SKU and BRANDS.xls'),
  ('933', 'FENADIN SUSPENSION 50ML', 'Suspension', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('103', 'FUROCEF 750MG IM/IV INJ', 'Injection', '750MG', 'Renata All SKU and BRANDS.xls'),
  ('S72', 'FUROCEF DS SUSPENSION 50ML 1X1''S', 'Suspension', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('099', 'FUROCEF FC 125MG TAB 10''S', 'Tablet', '125MG', 'Renata All SKU and BRANDS.xls'),
  ('927', 'FUROCEF FC 250MG TAB (2X8''S)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('264', 'FUROCEF FC 500MG TAB (2X6''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('104', 'FUROCEF FC IM/IV INJ 1.5GM', 'Injection', '1.5GM', 'Renata All SKU and BRANDS.xls'),
  ('973', 'FUROCEF FC IM/IV INJ 1GM', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('102', 'FUROCEF FC SUSPENSION 70ML', 'Suspension', '70ML', 'Renata All SKU and BRANDS.xls'),
  ('N77', 'FUROCLAV 250MG TAB 2X7''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('N78', 'FUROCLAV 500MG TAB 2X7''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SI1', 'FUROCLAV 70ML DRY PWD SUSP 1X1''S', 'Suspension', '70ML', 'Renata All SKU and BRANDS.xls'),
  ('C81', 'MAXPRO 20MG CAP 10X14''S', 'Capsule', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('C72', 'MAXPRO 40MG CAP 10X10''S', 'Capsule', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('N55', 'MAXPRO EC 20MG TAB 10X14''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('C39', 'MAXPRO EC 40MG TAB 6X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('N31', 'MAXPRO HP 20MG (14X4''S)', 'Medicine', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('015', 'MAXPRO INJ 40MG', 'Injection', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('S21', 'MAXPRO MUPS 20MG TAB 4X14''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('C8Y', 'MAXPRO MUPS 20MG TAB 5X14''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('CF5', 'MAXPRO MUPS 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('641', 'MICROGEST 100MG SOFT CAP 3X10''S', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('642', 'MICROGEST 200MG SOFT CAP 3X10''S', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C64', 'MICROGEST 400MG VAGINAL PESSARY 2X5''S', 'Medicine', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('C8I', 'MICROGEST AQ-25 INJ 1X5''S', 'Injection', '', 'Renata All SKU and BRANDS.xls'),
  ('885', 'NEUROBEST FC TAB 6X10''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('254', 'NEUROBEST INJ 3ML 2X5''S', 'Injection', '3ML', 'Renata All SKU and BRANDS.xls'),
  ('N60', 'NORMENS 5MG TAB 10X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('N68', 'ODMON 4MG CHEWABLE TAB 3X10''S', 'Tablet', '4MG', 'Renata All SKU and BRANDS.xls'),
  ('C79', 'ODMON FC 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C78', 'ODMON FC 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('911', 'ORCEF 200MG CAP (2X8''S)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('298', 'ORCEF 200MG TAB (2X6''S)', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SL2', 'ORCEF 21ML PEDIATRIC DROP 1X1''S', 'Drops', '21ML', 'Renata All SKU and BRANDS.xls'),
  ('C41', 'ORCEF 400MG CAP (2X6''S)', 'Capsule', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('C40', 'ORCEF 400MG TAB (2X6''S)', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('C18', 'ORCEF 50ML DS DPS 1X1''S', 'Suspension', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('237', 'ORCEF DPS 30ML', 'Suspension', '30ML', 'Renata All SKU and BRANDS.xls'),
  ('236', 'ORCEF DPS 40ML', 'Suspension', '40ML', 'Renata All SKU and BRANDS.xls'),
  ('221', 'ORCEF DPS 50ML', 'Suspension', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('609', 'ORCEF DPS 70ML', 'Suspension', '70ML', 'Renata All SKU and BRANDS.xls'),
  ('926', 'RENXIT FC TAB (10X10''S)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('S64', 'REPHASTON 10MG TAB 2X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C2N', 'REPHASTON 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('S56', 'ROLAC 30MG INJ 1ML 1''S', 'Injection', '30MG, 1ML', 'Renata All SKU and BRANDS.xls'),
  ('S57', 'ROLAC 60MG INJ 2ML 1''S', 'Injection', '60MG, 2ML', 'Renata All SKU and BRANDS.xls'),
  ('N16', 'ROLAC FC 10MG TAB (4X14''S)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('155', 'ROLAC INJ 10MG 1ML', 'Injection', '10MG, 1ML', 'Renata All SKU and BRANDS.xls'),
  ('SL8', 'ROLAC MDT 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CO7', 'ROLAC NASAL SPRAY 1X1''S', 'Spray', '', 'Renata All SKU and BRANDS.xls'),
  ('N07', 'ROLIP 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C15', 'ROLIP 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('SE4', 'ROLIP FC 20MG TAB 2X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('CV7', 'ROLIP FC 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('S75', 'THYROX 100MCG TAB 60X1''S', 'Tablet', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('C7V', 'THYROX 12.5MCG TAB 100X1''S', 'Tablet', '12.5MCG', 'Renata All SKU and BRANDS.xls'),
  ('C65', 'THYROX 25MCG TAB 100X1''S', 'Tablet', '25MCG', 'Renata All SKU and BRANDS.xls'),
  ('N5A', 'THYROX 25MCG TAB 3X30''S', 'Tablet', '25MCG', 'Renata All SKU and BRANDS.xls'),
  ('CM1', 'THYROX 75MCG TAB 1X60''S', 'Tablet', '75MCG', 'Renata All SKU and BRANDS.xls'),
  ('955', 'THYROX TAB 50MCG (3X30''S)', 'Tablet', '50MCG', 'Renata All SKU and BRANDS.xls'),
  ('N79', 'ZITHRIN 250MG CAP (3X5''S)', 'Capsule', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('N61', 'ZITHRIN 250MG TAB (3X5''S)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('834', 'ZITHRIN 30ML SUSPENSION 1''S', 'Suspension', '30ML', 'Renata All SKU and BRANDS.xls'),
  ('173', 'ZITHRIN DRY SYRUP 15ML', 'Syrup', '15ML', 'Renata All SKU and BRANDS.xls'),
  ('270', 'ZITHRIN DRY SYRUP 20ML', 'Syrup', '20ML', 'Renata All SKU and BRANDS.xls'),
  ('271', 'ZITHRIN DRY SYRUP 35ML', 'Syrup', '35ML', 'Renata All SKU and BRANDS.xls'),
  ('290', 'ZITHRIN DRY SYRUP 50ML', 'Syrup', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('N27', 'ZITHRIN FC 500MG TAB (3X5''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('620', 'ZITHRIN IV INJ 1''S', 'Injection', '', 'Renata All SKU and BRANDS.xls'),
  ('S71', 'ZODEF 24MG TAB 2X10''S', 'Tablet', '24MG', 'Renata All SKU and BRANDS.xls'),
  ('CO6', 'ZODEF 60ML SUSP 1X1''S', 'Suspension', '60ML', 'Renata All SKU and BRANDS.xls'),
  ('S70', 'ZODEF 6MG TAB 3X10''S', 'Tablet', '6MG', 'Renata All SKU and BRANDS.xls'),
  ('C4D', 'ZODEF FC 18MG TAB 2X10''S', 'Tablet', '18MG', 'Renata All SKU and BRANDS.xls'),
  ('C4E', 'ZODEF FC 30MG TAB 1X10''S', 'Tablet', '30MG', 'Renata All SKU and BRANDS.xls'),
  ('C4Y', 'ZODEF FC 36MG TAB 1X10''S', 'Tablet', '36MG', 'Renata All SKU and BRANDS.xls'),
  ('SQ1', 'ALKANON 500MG TAB 5X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SQ2', 'ALKANON 750MG TAB 4X6''S', 'Tablet', '750MG', 'Renata All SKU and BRANDS.xls'),
  ('CG1', 'ALKANON DT 1000MG TAB 3X4''S', 'Tablet', '1000MG', 'Renata All SKU and BRANDS.xls'),
  ('CR2', 'DECAREN SG 100MG CAP 3X10''S', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('CR3', 'DECAREN SG 200MG CAP 4X5''S', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SD9', 'DECAREN SG 60MG CAP 3X10''S', 'Capsule', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('S69', 'DENIXIL 0.25MG TAB 5X10''S', 'Tablet', '0.25MG', 'Renata All SKU and BRANDS.xls'),
  ('894', 'DENIXIL 0.5MG TAB 5X10''S', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('CL3', 'DENIXIL 0.5MG TAB 8X10''S', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C60', 'DENIXIL 1MG TAB 5X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('895', 'DENIXIL 2MG TAB 3X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('CZ1', 'DENIXIL RAPID 0.25MG TAB 5X10''S', 'Tablet', '0.25MG', 'Renata All SKU and BRANDS.xls'),
  ('C1C', 'DENIXIL RAPID 0.50MG TAB 5X10''S', 'Tablet', '0.50MG', 'Renata All SKU and BRANDS.xls'),
  ('C7D', 'ESCILEX 100ML SYRUP 1X1''S', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('SA9', 'ESCILEX 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CF9', 'ESCILEX 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('SA8', 'ESCILEX 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C7C', 'ESCILEX ODT 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C9R', 'ESCILEX ODT 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('N50', 'GABA-P 25MG CAPS 5X6''S', 'Capsule', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('967', 'GABA-P 50MG CAP (3X10''S)', 'Capsule', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('C9C', 'GABA-P 50MG CAP 3X14''S', 'Capsule', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('899', 'GABA-P 75MG CAP (3X10''S)', 'Capsule', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('C9D', 'GABA-P 75MG CAP 3X12''S', 'Capsule', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('CG5', 'GABA-P CR 165MG TAB 5X6''S', 'Tablet', '165MG', 'Renata All SKU and BRANDS.xls'),
  ('SW2', 'GABA-P CR 330MG TAB 5X6''S', 'Tablet', '330MG', 'Renata All SKU and BRANDS.xls'),
  ('CG4', 'GABA-P CR 82.5MG TAB 5X6''S', 'Tablet', '82.5MG', 'Renata All SKU and BRANDS.xls'),
  ('SP4', 'GLINTA FC 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C5G', 'GLINTA PLUS FC 10/5MG TABS 2X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C5H', 'GLINTA PLUS FC 25/5MG TABS 2X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('S85', 'GLINTA-M 500MG TAB 3X10''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('S86', 'GLINTA-M 850MG TAB 5X6''S', 'Tablet', '850MG', 'Renata All SKU and BRANDS.xls'),
  ('CX3', 'HYDROGEST 1ML (250MG/ML) INJ 1X1''S', 'Injection', '1ML, 250MG', 'Renata All SKU and BRANDS.xls'),
  ('CY7', 'HYDROGEST DS 2ML (500MG/2ML) INJ 1X1''S', 'Injection', '2ML, 500MG/2ML', 'Renata All SKU and BRANDS.xls'),
  ('N13', 'PLAGRIN 75MG TAB (3X10''S)', 'Tablet', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('N14', 'PLAGRIN PLUS 75+75MG TAB (3X10''S)', 'Tablet', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('CP8', 'SALTICA HFA 25/125MCG MDI(120PUFF) 1''S', 'Medicine', '125MCG', 'Renata All SKU and BRANDS.xls'),
  ('CP7', 'SALTICA HFA 25/250MCG MDI(120PUFF) 1''S', 'Medicine', '250MCG', 'Renata All SKU and BRANDS.xls'),
  ('CQ4', 'SALTICA HFA 25/250MCG REFILL(120PUFF)1''S', 'Medicine', '250MCG', 'Renata All SKU and BRANDS.xls'),
  ('C7X', 'SALTICA RENACAP 50/100MCG (DPI) CAP 5X10''S', 'Capsule', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('CP4', 'SALTICA RENACAP 50/250MCG (DPI) CAP 3X10S', 'Capsule', '250MCG', 'Renata All SKU and BRANDS.xls'),
  ('CP5', 'SALTICA RENACAP 50/500MCG (DPI) CAP 3X10S', 'Capsule', '500MCG', 'Renata All SKU and BRANDS.xls'),
  ('CI5', 'TELPRO 20MG TAB 2X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('SH8', 'TELPRO 40MG TAB 2X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('SH9', 'TELPRO 80MG TAB 2X6''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('C9P', 'TELPRO FC 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('C9Q', 'TELPRO FC 80MG TAB 3X6''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('SJ3', 'TELPRO MAX 40MG TAB 2X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('SJ4', 'TELPRO MAX 80MG TAB 2X10''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('N1F', 'TELPRO MAX FC 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('N1G', 'TELPRO MAX FC 80MG TAB 3X10''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('CI6', 'TELPRO PLUS FC 40MG TAB 2X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('CI7', 'TELPRO PLUS FC 80MG TAB 2X10''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('N98', 'AB KIT 1X5''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N46', 'ANDROCAP 40MG CAP 3X10''S', 'Capsule', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('C32', 'ANGELA TAB 1X28''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('CU9', 'ANTOGIN ER 500MG TAB 5X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N64', 'ARBECIN 1ML IV INJ 1X1''S', 'Injection', '1ML', 'Renata All SKU and BRANDS.xls'),
  ('S25', 'AZISAN 80MG TAB 2X10''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('S26', 'AZISAN FC 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('S24', 'AZISAN PLUS 40MG TAB 2X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('022', 'BACTAMOX 250MG TAB 100''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('023', 'BACTAMOX 500MG TAB (5X10''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('033', 'BECONEX SYRUP 100ML', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('034', 'BECONEX SYRUP 200ML', 'Syrup', '200ML', 'Renata All SKU and BRANDS.xls'),
  ('233', 'BECONEX ZI SYRUP 100ML', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('924', 'BECOSULES GOLD CAP (6X15''S)', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('SB2', 'BETATIN 16MG TAB 6X10''S', 'Tablet', '16MG', 'Renata All SKU and BRANDS.xls'),
  ('SB1', 'BETATIN 8MG TAB 10X10''S', 'Tablet', '8MG', 'Renata All SKU and BRANDS.xls'),
  ('037', 'BIGMET FC 500MG TAB 10X10''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('038', 'BIGMET FC 850MG TAB 10X10''S', 'Tablet', '850MG', 'Renata All SKU and BRANDS.xls'),
  ('875', 'BREDICON 75MCG TAB (1X28''S)', 'Tablet', '75MCG', 'Renata All SKU and BRANDS.xls'),
  ('832', 'CABOLIN TAB  0.50MG 2X2''S', 'Tablet', '0.50MG', 'Renata All SKU and BRANDS.xls'),
  ('C31', 'CALCEFER EFFERVESCENT TAB 1X10''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('039', 'CALCIN 1.25MG TAB 50''S', 'Tablet', '1.25MG', 'Renata All SKU and BRANDS.xls'),
  ('608', 'CALCIN-D FC TAB 15''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('896', 'CALCIN-D TAB 30''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('934', 'CALCIN-D TAB 6X10''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C26', 'CALCIN-DX TAB 1X30''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('619', 'CALCIN-M TAB 30''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('883', 'CALCIN-M TAB 40''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C16', 'CALCIN-O DS FC 740MG TAB 3X10''S', 'Tablet', '740MG', 'Renata All SKU and BRANDS.xls'),
  ('C29', 'CALCIN-O FC 400MG TAB (CONTAINER) 1X30''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('N40', 'CALCIN-O FC 400MG TAB 3X10''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('S22', 'CALCIN-O KIT 1X61''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N41', 'CARDIPIN 5MG TAB 6X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('N42', 'CARDIPIN PLUS 5MG TAB (6X10''S)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('S17', 'CARTILAGE MAX FC TAB 3X10''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('255', 'CARTILAGE PLUS TAB (5X6''S)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C28', 'CEBUTEN 400MG CAP 2X7''S', 'Capsule', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('005', 'CECLOFEN 100MG TAB (5X10''S)', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('051', 'CEFAZID IV/IM INJ 1GM', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('181', 'CEFAZID IV/IM INJ 250MG', 'Injection', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('050', 'CEFAZID IV/IM INJ 500MG', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('240', 'CEFOTAX IM/IV INJ 1GM', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('242', 'CEFOTAX IM/IV INJ 250MG', 'Injection', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('243', 'CEFOTAX IM/IV INJ 500MG', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('053', 'CEFTIPIME IM/IV INJ 1GM', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('054', 'CEFTIPIME IM/IV INJ 2GM', 'Injection', '2GM', 'Renata All SKU and BRANDS.xls'),
  ('052', 'CEFTIPIME IM/IV INJ 500MG', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('046', 'CEFTIZONE IM INJ 1GM', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('044', 'CEFTIZONE IM INJ 250MG', 'Injection', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('045', 'CEFTIZONE IM INJ 500MG', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('049', 'CEFTIZONE IV INJ 1GM', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('047', 'CEFTIZONE IV INJ 250MG', 'Injection', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('204', 'CEFTIZONE IV INJ 2GM', 'Injection', '2GM', 'Renata All SKU and BRANDS.xls'),
  ('048', 'CEFTIZONE IV INJ 500MG', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('S63', 'CILMA 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('S65', 'CILMA 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('067', 'CONASYD 1% DER. CREAM 10GM', 'Cream', '10GM', 'Renata All SKU and BRANDS.xls'),
  ('974', 'COVAN 1G IV INFUSION 1X1''S', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('975', 'COVAN 500MG IV INFUSION 1X1''S', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('960', 'CRIPTINE 2.5MG TAB 30''S', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('612', 'DANZOL 100MG CAP (3X10''S)', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('613', 'DANZOL 200MG CAP (2X10''S)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('073', 'DELENTIN SUSPENSION 10ML 1''S', 'Suspension', '10ML', 'Renata All SKU and BRANDS.xls'),
  ('262', 'DELTASONE 10MG TAB (10X10''S)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('263', 'DELTASONE 20MG TAB (5X10''S)', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('N54', 'DELTASONE 5MG TAB (25X10''S)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CS7', 'DELTASONE 5MG TAB 17X30''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C4Z', 'DELTASONE 5MG TAB 9X30''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('637', 'DELTASONE ORAL SOLUTION 100ML 1''S', 'Solution', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('636', 'DELTASONE ORAL SOLUTION 50ML 1''S', 'Solution', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('959', 'DESOLON TAB 1X21''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('078', 'DEXA IM/IV INJ 5MG/ML 10''S', 'Injection', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('076', 'DEXATAB 0.5MG 25X10''S', 'Medicine', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('S83', 'DIAMPA 10MG TAB 2X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('S84', 'DIAMPA 25MG TAB 1X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('N1H', 'DIAMPA FC 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('SZ9', 'DIAMPA-M FC 500MG TAB 3X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N15', 'DOMIREN 10MG TAB 15X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('287', 'DOMIREN PAEDIATRIC DROPS 15ML', 'Drops', '15ML', 'Renata All SKU and BRANDS.xls'),
  ('990', 'DOMIREN SUSPENSION 100ML 1X1''S', 'Suspension', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('286', 'DOMIREN SUSPENSION 60ML', 'Suspension', '60ML', 'Renata All SKU and BRANDS.xls'),
  ('081', 'DOXICAP 100MG CAP (10X10''S)', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('639', 'DYSMEN 500MG (5X10''S)', 'Medicine', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('S18', 'EAZY JELLY 50GM TUBE 1''S', 'Medicine', '50GM', 'Renata All SKU and BRANDS.xls'),
  ('941', 'E-GEL CAP  200MG (10X10''S)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('940', 'E-GEL DS CAP 400MG  (5X10''S)', 'Capsule', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('SB5', 'ELAZOL FC 200MG TAB 2X4''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SB4', 'ELAZOL FC 50MG TAB 2X4''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('633', 'EMCON-1 TAB 1.5MG (1X1''S)', 'Tablet', '1.5MG', 'Renata All SKU and BRANDS.xls'),
  ('978', 'EMEREN 4MG TAB (3X10''S)', 'Tablet', '4MG', 'Renata All SKU and BRANDS.xls'),
  ('840', 'EMEREN 50ML SYRP 1X1''S', 'Syrup', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('979', 'EMEREN 8MG TAB 3X10''S', 'Tablet', '8MG', 'Renata All SKU and BRANDS.xls'),
  ('980', 'EMEREN IM/IV 8MG/4ML INJ 1X5''S', 'Injection', '8MG/4ML', 'Renata All SKU and BRANDS.xls'),
  ('SP9', 'EPICET 1000MG XR 2X6''S', 'Medicine', '1000MG', 'Renata All SKU and BRANDS.xls'),
  ('S89', 'EPICET 100ML ORAL SOLUTION 1X1''S', 'Solution', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('SP7', 'EPICET 500MG XR 2X6''S', 'Medicine', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SO8', 'EPICET 5ML(500MG/5ML) INJ 1X5''S', 'Injection', '5ML, 500MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('SP8', 'EPICET 750MG XR 2X6''S', 'Medicine', '750MG', 'Renata All SKU and BRANDS.xls'),
  ('S88', 'EPICET FC 250MG TAB 2X10''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('S87', 'EPICET FC 500MG 1X10''S', 'Medicine', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('CG3', 'EPICET XR 1500MG TAB 3X4''S', 'Tablet', '1500MG', 'Renata All SKU and BRANDS.xls'),
  ('948', 'EPIDRON INJ 5ML (1X5''S)', 'Injection', '5ML', 'Renata All SKU and BRANDS.xls'),
  ('S41', 'ERPEN IV 1G INJ 1X1''S', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('085', 'ERYTHROX SUSPENSION 100ML 1''S', 'Suspension', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('S59', 'ESTRACON 15G VAGINAL CREAM 1X1''S', 'Cream', '15G', 'Renata All SKU and BRANDS.xls'),
  ('N11', 'ESTRACON FC TAB 0.625MG 3X10''S', 'Tablet', '0.625MG', 'Renata All SKU and BRANDS.xls'),
  ('N04', 'FEBUREN 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('N05', 'FEBUREN 80MG TAB 1X10''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('850', 'FENOBATE 200MG CAB 5X6''S', 'Medicine', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('N25', 'FENTANYL 100MCG/2ML IV INJ 5X1''S', 'Injection', '100MCG/2ML', 'Renata All SKU and BRANDS.xls'),
  ('640', 'FERISTAR 5ML INJ (1X1''S)', 'Injection', '5ML', 'Renata All SKU and BRANDS.xls'),
  ('C25', 'FERIX-V CAP 6X10''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('095', 'FLONTIN 250MG TAB (2X10''S)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('096', 'FLONTIN 500MG TAB (3X10''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('196', 'FLONTIN 750MG  TAB 20''S', 'Tablet', '750MG', 'Renata All SKU and BRANDS.xls'),
  ('914', 'FLONTIN IV INFUSION 100ML', 'Injection', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('226', 'FLONTIN SUSPENSION 60ML', 'Suspension', '60ML', 'Renata All SKU and BRANDS.xls'),
  ('N33', 'FLUSTAR 100ML DRY SYS 1X1''S', 'Medicine', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('606', 'FLUSTAR 250MG  CAP (12X4''S)', 'Capsule', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('607', 'FLUSTAR 500MG  CAP (7X4''S)', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('063', 'GABA 300MG TAB (3X10''S)', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('N80', 'GESTRENOL 5MG TAB 5X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('958', 'GIANE 35MG TAB 21''S', 'Tablet', '35MG', 'Renata All SKU and BRANDS.xls'),
  ('176', 'GLICRON 80MG TAB (3X10''S)', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('175', 'GLICRON CR 30MG CAP (3X10''S)', 'Capsule', '30MG', 'Renata All SKU and BRANDS.xls'),
  ('T45', 'GOODGUT VEG CAP 5X6''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('N34', 'GYNOVA 2MG TAB 3X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('S91', 'HAEMACCEL 500ML SOLUTION 1X1''S', 'Solution', '500ML', 'Renata All SKU and BRANDS.xls'),
  ('232', 'HONYCOL LINCTUS 100ML', 'Medicine', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('602', 'HONYCOL LINCTUS 200ML', 'Medicine', '200ML', 'Renata All SKU and BRANDS.xls'),
  ('N08', 'INDULA 200MCG TAB 3X10''S', 'Tablet', '200MCG', 'Renata All SKU and BRANDS.xls'),
  ('012', 'IROPEN IV 500MG INJ', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N22', 'IVANA 150MG TAB 1X1''S', 'Tablet', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('882', 'KAIN INJ 10ML (1X1''S)', 'Injection', '10ML', 'Renata All SKU and BRANDS.xls'),
  ('058', 'KIDDI SYRUP 100ML', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('121', 'KIDDI SYRUP 200M', 'Syrup', '', 'Renata All SKU and BRANDS.xls'),
  ('N10', 'LETROL 2.5MG TAB 2X5''S', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('206', 'LEVOKING  500MG TAB (5X6''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('936', 'LEVOKING 100ML ORAL SOLUTION', 'Solution', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('605', 'LUCAN-R 150MG CAP (2X6''S)', 'Capsule', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('621', 'LUCAN-R 200MG CAP (2X6''S)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C73', 'LUCAN-R 50MG CAP (5X10''S)', 'Capsule', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('112', 'LUCAN-R SUSPENSION 35ML', 'Suspension', '35ML', 'Renata All SKU and BRANDS.xls'),
  ('888', 'LUCENT SOFT GELATIN CAP (3X10''S)', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('S58', 'MANTADIN 100MG CAP 2X14''S', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('646', 'MAXOLAX 10MG TAB (3X10''S)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('645', 'MAXOLAX 5MG TAB (3X10''S)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('018', 'MAZIC 10MG/5ML 100ML', 'Medicine', '10MG/5ML, 100ML', 'Renata All SKU and BRANDS.xls'),
  ('016', 'MAZIC JR 100ML  4.05MG/5ML SYRP 1X1''S', 'Syrup', '100ML, 4.05MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('615', 'MEDROGEST 10MG TAB', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('877', 'MEDROGEST 5MG TAB', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('951', 'MENOREST 2.5MG TAB (1X28''S)', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('N76', 'MEROPEN 250MG IV INJ (1X1''S)', 'Injection', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('251', 'MEROPEN IV 1GM INJ', 'Injection', '1GM', 'Renata All SKU and BRANDS.xls'),
  ('275', 'MEROPEN IV 500MG INJ', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N09', 'MIF FC 200MG TAB 1X3''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C4F', 'MIGESIC 200MG TAB 5X6''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SH3', 'MITAPRO 15MG TAB 3X10''S', 'Tablet', '15MG', 'Renata All SKU and BRANDS.xls'),
  ('938', 'NANDRON 25MG 1ML (5X1''S)', 'Medicine', '25MG, 1ML', 'Renata All SKU and BRANDS.xls'),
  ('939', 'NANDRON 50MG 1ML', 'Medicine', '50MG, 1ML', 'Renata All SKU and BRANDS.xls'),
  ('C17', 'NEOGEST 2MG TAB 1X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('N2Y', 'NEOGEST 2MG TAB 2X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('881', 'NEOS-R INJ 1ML (1X5''S)', 'Injection', '1ML', 'Renata All SKU and BRANDS.xls'),
  ('644', 'NEOS-R INJ 5ML (1X5''S)', 'Injection', '5ML', 'Renata All SKU and BRANDS.xls'),
  ('SQ7', 'NITROREN SR 2.6MG TAB 3X10''S', 'Tablet', '2.6MG', 'Renata All SKU and BRANDS.xls'),
  ('179', 'NORMANAL 500MG FC TAB (3X10''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('282', 'NORRY 3MG TAB (5X10''S)', 'Tablet', '3MG', 'Renata All SKU and BRANDS.xls'),
  ('S74', 'NOVELON LITE FC TAB 1X28''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('S73', 'NOVELON-28 FC TAB 1X28''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('247', 'OSTAN 25MG TABS 3X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('N43', 'OSTAN FC 50MG TAB 5X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('943', 'OSTAN PLUS 50MG TAB (3X10''S)', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('956', 'OVULET 100MG TAB (1X5''S)', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('950', 'OVULET TAB 50MG(1X10''S)', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('937', 'OXYTON 1ML(5IU/ML) INJ (1X10''S)', 'Injection', '1ML, 5IU', 'Renata All SKU and BRANDS.xls'),
  ('C67', 'OXYTON DS 1ML 10IU INJ 1X10''S', 'Injection', '1ML, 10IU', 'Renata All SKU and BRANDS.xls'),
  ('S34', 'PANGESIC TAB 5X6''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C2Y', 'PCAB FC 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C2Z', 'PCAB FC 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('891', 'PENDORIL 2MG TAB (2X10''S)', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('892', 'PENDORIL 4MG TAB (2X10''S)', 'Tablet', '4MG', 'Renata All SKU and BRANDS.xls'),
  ('889', 'PENDORIL PLUS 2MG TAB 2X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('890', 'PENDORIL PLUS 4MG TAB 2X10''S', 'Tablet', '4MG', 'Renata All SKU and BRANDS.xls'),
  ('614', 'PHENOCEPT TABS', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('S54', 'PRAZOLE 20MG CAP 5X14''S', 'Capsule', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('C12', 'PREROID 5MG TAB 1X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('266', 'PROTONIL EC 20MG TAB 5X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('267', 'PROTONIL EC 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('S20', 'PULMINO 200MG TAB 5X6''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C49', 'PULMINO FC 400MG TAB 5X6''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('297', 'PUSHTIKONA 1X30''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('145', 'PYRALGIN 500MG TAB (50X10''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('146', 'PYRALGIN ORAL SUSPENSION 60ML', 'Suspension', '60ML', 'Renata All SKU and BRANDS.xls'),
  ('626', 'QCIN 150MG CAP (5X6''S)', 'Capsule', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('627', 'QCIN 300MG CAP (5X6''S)', 'Capsule', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('635', 'RECOF 100ML SYRUP (1X1''S)', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('839', 'RECOF 15ML PEAD DROPS 1X1''S', 'Drops', '15ML', 'Renata All SKU and BRANDS.xls'),
  ('N49', 'RECOX FC 120MG TAB 2X10''S', 'Tablet', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('N48', 'RECOX FC 60MG TAB 3X10''S', 'Tablet', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('N47', 'RECOX FC 90MG TAB 2X10''S', 'Tablet', '90MG', 'Renata All SKU and BRANDS.xls'),
  ('878', 'REGUMEN TAB (1X21''S)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('SL7', 'RENACID 200ML SUSPENSION 1''S', 'Suspension', '200ML', 'Renata All SKU and BRANDS.xls'),
  ('295', 'RENAMYCIN 250MG CAP 60''S', 'Capsule', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('CL4', 'REZOR FC 10MG TAB 2X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('S81', 'REZOR FC 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('S80', 'REZOR FC 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('S79', 'REZOR MAX FC 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('S78', 'REZOR MAX FC 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('153', 'RM INJ 10ML VIAL', 'Injection', '10ML', 'Renata All SKU and BRANDS.xls'),
  ('152', 'RM OTIC SOLUTION 5MG', 'Solution', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CP6', 'SALBUREN HFA 100MCG MDI(200PUFF) 1''S', 'Medicine', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('CQ5', 'SALBUREN HFA 100MCG REFILL(200PUFF) 1''S', 'Medicine', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('CQ6', 'SALBUREN-I HFA 100/20MCG (200PUFF) 1''S', 'Medicine', '20MCG', 'Renata All SKU and BRANDS.xls'),
  ('CQ7', 'SALBUREN-I HFA 100/20MCG REFILL(200PUFF) 1''S', 'Medicine', '20MCG', 'Renata All SKU and BRANDS.xls'),
  ('261', 'SERONEX 100MG TAB 3X10''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('170', 'SERONEX 25MG TAB 5X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('235', 'SERONEX 50MG TAB 5X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('S60', 'SITACRET-M 500MG TAB 2X10''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('880', 'SIVICAINE HEAVY INJ 4ML (1X5''S)', 'Injection', '4ML', 'Renata All SKU and BRANDS.xls'),
  ('SQ3', 'SPERID (1MG/ML) 100ML SYRP 1X1''S', 'Syrup', '1MG, 100ML', 'Renata All SKU and BRANDS.xls'),
  ('126', 'SPERID 1MG TAB 5X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('S62', 'SPERID 2MG TAB 3X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('S61', 'SPERID 4MG TAB 3X10''S', 'Tablet', '4MG', 'Renata All SKU and BRANDS.xls'),
  ('C5B', 'SPERID ODT 0.5MG TAB 5X10''S', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C5C', 'SPERID ODT 1MG TAB 5X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('C5D', 'SPERID ODT 2MG TAB 5X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('C5E', 'SPERID ODT 3MG TAB 5X10''S', 'Tablet', '3MG', 'Renata All SKU and BRANDS.xls'),
  ('C5F', 'SPERID ODT 4MG TAB 5X6''S', 'Tablet', '4MG', 'Renata All SKU and BRANDS.xls'),
  ('C83', 'STARK 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C82', 'STARK 60ML ORAL SOLUTION 1X1''S', 'Solution', '60ML', 'Renata All SKU and BRANDS.xls'),
  ('161', 'TAVEN 10MG FC TAB 30''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('162', 'TAVEN 20MG FC TAB 30''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('625', 'TAVEN 40MG FC TAB 30''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('C1W', 'TAVEN EZ 10/10MG TAB 2X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C1X', 'TAVEN EZ 20/10MG TAB 2X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N37', 'TAZOPEN 2.25GM IV INFUSION', 'Injection', '2.25GM', 'Renata All SKU and BRANDS.xls'),
  ('623', 'TAZOPEN 4.5GM INJ (1X1''S)', 'Injection', '4.5GM', 'Renata All SKU and BRANDS.xls'),
  ('SY5', 'TERBIMAX 10G CREAM 1X1''S', 'Cream', '10G', 'Renata All SKU and BRANDS.xls'),
  ('SL9', 'TERBIMAX 250MG TAB 1X14''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('N39', 'TIGOVER FC 10MG TAB 5X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N38', 'TIGOVER FC 5MG TAB 5X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('617', 'TOPMATE 25MG TAB (5X10''S)', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('618', 'TOPMATE 50MG TAB (5X10''S)', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('918', 'TOTIFEN 1MG TAB 10X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('919', 'TOTIFEN SYRUP 100ML', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('C87', 'TRIZEDON MR 35MG TAB 3X10''S', 'Tablet', '35MG', 'Renata All SKU and BRANDS.xls'),
  ('299', 'TRULAX SYRUP 1MG/5ML 100ML 1''S', 'Syrup', '1MG/5ML, 100ML', 'Renata All SKU and BRANDS.xls'),
  ('831', 'URITONE 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('833', 'URITONE 40MG TAB 3X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('SL6', 'VALPORIN 100ML SYRUP 1''S', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('SL3', 'VALPORIN CR 200MG TAB 5X10''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SL4', 'VALPORIN CR 300MG TAB 5X6''S', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('SL5', 'VALPORIN CR 500MG TAB 5X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('S51', 'VITA D3 (200000IU/1ML) INJ 1X1''S', 'Injection', '200000IU/1ML', 'Renata All SKU and BRANDS.xls'),
  ('S15', 'VITA D3 20000 IU CAP 2X5''S', 'Capsule', '20000IU', 'Renata All SKU and BRANDS.xls'),
  ('S16', 'VITA D3 40000 IU CAP 2X5''S', 'Capsule', '40000IU', 'Renata All SKU and BRANDS.xls'),
  ('CK1', 'VITA-D3 1000 IU TAB 3X10''S', 'Tablet', '1000IU', 'Renata All SKU and BRANDS.xls'),
  ('CK2', 'VITA-D3 2000 IU TAB 3X10''S', 'Tablet', '2000IU', 'Renata All SKU and BRANDS.xls'),
  ('SH7', 'VOMIREN 0.075MG/1.5ML INJ 1X5''S', 'Injection', '0.075MG/1.5ML', 'Renata All SKU and BRANDS.xls'),
  ('SH6', 'VOMIREN 0.25MG/5ML INJ 1X5''S', 'Injection', '0.25MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('S90', 'VOMIREN FC 0.5MG CAP 2X10''S', 'Capsule', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('S82', 'VOMIREN FC 0.5MG TAB 2X10''S', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('278', 'XAMIC 500MG CAP (2X10''S)', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C4T', 'XAMIC 650MG TAB 4X5''S', 'Tablet', '650MG', 'Renata All SKU and BRANDS.xls'),
  ('281', 'XAMIC IM/IV INJ  500MG (1X5''S)', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('021', 'XANITA 30ML ORAL SUSPENSION 1''S', 'Suspension', '30ML', 'Renata All SKU and BRANDS.xls'),
  ('041', 'XANITA 60ML ORAL SUSPENSION 1''S', 'Suspension', '60ML', 'Renata All SKU and BRANDS.xls'),
  ('062', 'XANITA FC TAB 500MG (3X6''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('647', 'XENAPRO 500MG TAB (5X6''S)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C21', 'XENAPRO PLUS 500MG TAB 5X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C75', 'XENAPRO PLUS DR 375MG TAB 5X6''S', 'Tablet', '375MG', 'Renata All SKU and BRANDS.xls'),
  ('N3K', '10MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3L', '12MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3E', '4MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3F', '5MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3G', '6MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3H', '7MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3I', '8MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N3J', '9MM EASYGRIP INTEGRATED WINGED BASE CANNULA 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C9E', 'ALGIN 100ML SYRP 1X1''S (BGD-DGDP)', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('C5J', 'ALGIN 100ML SYRP 1X1''S (BGD-LGI)', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('C1B', 'ALGIN 50MG TAB 10X10''S (BGD-LGI)', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SJ9', 'ALPHAPRESS 1MG TAB 10X10''S (BGD-LGI)', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('CH4', 'ALZACARE ER 14/10MG CAP 3X6''S', 'Capsule', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CH5', 'ALZACARE ER 21/10MG CAP 3X6''S', 'Capsule', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CH6', 'ALZACARE ER 28/10MG CAP 3X6''S', 'Capsule', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CH7', 'ALZACARE ER 7/10MG CAP 3X6''S', 'Capsule', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CQ8', 'AMLODIPINE BESYLATE AND ATENOLOL TABS. 6X10S (BGD-CLINICA)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C7W', 'ANDROJET IM 1ML INJ 1X1''S', 'Injection', '1ML', 'Renata All SKU and BRANDS.xls'),
  ('C6Q', 'ANTOGIN ER 500MG TAB 5X6''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N5Y', 'APON TAB 2X28''S (BGD-DGFP)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('CL1', 'ARIDE FC 100MG TAB 2X10''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('CL2', 'ARIDE FC 200MG TAB 2X5''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SO7', 'ARIDE FC 50MG TAB 3X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SM5', 'ATORVASTATINE 10MG TAB 3X10''S(BGD-CLINICA)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CA2', 'AZITHROMYCIN DIHYDRATE FC 500MG TAB 3X5''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C4N', 'BEAUTIN FC 1MG TAB 3X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('C4O', 'BEAUTIN FC 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('SQ4', 'BENAZIN 12.5MG TAB 3X10''S', 'Tablet', '12.5MG', 'Renata All SKU and BRANDS.xls'),
  ('SQ5', 'BENAZIN 25MG TAB 3X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('C1T', 'BENAZIN FC 25MG TAB 3X10''S (BGD-LGI)', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('SV8', 'BENDOPA 100MG DISPERSIBLE TAB 5X6''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('SZ2', 'BENDOPA 200MG TAB 5X6''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('SV7', 'BENDOPA 50MG DISPERSIBLE TAB 5X6''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SX3', 'BISOPROLOL FUMARATE 2.5MG TAB 3X10''S(BGD-CLINICA)', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C5V', 'BISOREN 5MG TAB 3X10''S (BGD-LGI)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CE9', 'BREXPA FC 0.5MG TAB 3X10''S', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('CF1', 'BREXPA FC 1MG TAB 3X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('SY9', 'BRICET 100MG TAB 2X6''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('SY6', 'BRICET 25MG TAB 1X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('SY7', 'BRICET 50MG TAB 1X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SY8', 'BRICET 75MG TAB 1X10''S', 'Tablet', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('SJ2', 'CALCIN-D FC TAB 6X10''S (BGD-LGI)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('SM9', 'CALCIUM CARBONATE & VITAMIN-D FC TAB 6X10S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C8X', 'CALCIUM CARBONATE 1.25G TAB 5X10''S(BGD-CLINICA)', 'Tablet', '1.25G', 'Renata All SKU and BRANDS.xls'),
  ('N1V', 'CARDIPIN 5MG TAB 6X10''S (BGD-LGI)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('S42', 'CEE EFFERVESCENT TAB 1X10''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('CV5', 'CEFEPIME HCL IM/IV 1G INJ 50X1''S (BGD-CLINICA)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('C8L', 'CEFIXIME 200MG CAP 2X8''S (BGD-CLINICA)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('N3A', 'CEFTRIAXONE SODIUM IV 1G INJ 50X1''S (BGD-CLINICA)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('CF6', 'CEFUROXIME 500MG & CLAVOLANIC ACID 125MG TAB 2X7S', 'Tablet', '500MG, 125MG', 'Renata All SKU and BRANDS.xls'),
  ('CF7', 'CEFUROXIME AXETIL FC 500MG TAB 2X6S (BGD-CLINICA)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N3W', 'CEFUROXIME SODIUM IM/IV 750MG INJ. 100X1S (BGD)', 'Injection', '750MG', 'Renata All SKU and BRANDS.xls'),
  ('SN1', 'CILNIDIPINE FC 5MG TAB 3X10''S(BGD-CLINICA)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('SG4', 'CIPRAN 40MG CAP 3X6''S', 'Capsule', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('SG5', 'CIPRAN 80MG CAP 3X6''S', 'Capsule', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('CD5', 'CIPROFLOXACIN HCL 500MG TAB 3X10''S (BGD-CLINICA)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('987', 'CLAVOXIL FC 375MG TAB 3X6''S', 'Tablet', '375MG', 'Renata All SKU and BRANDS.xls'),
  ('N30', 'CLAVOXIL FC 625MG TAB 3X6''S', 'Tablet', '625MG', 'Renata All SKU and BRANDS.xls'),
  ('N3B', 'CLONAZEPAM 0.5MG TAB 8X10''S (BGD-CLINICA)', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('SN2', 'CLONAZEPAM 0.5MG TABS 5X10S (BGD-CLINICA)', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('CB9', 'CLONAZEPAM 2MG TAB 3X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('CH9', 'CLOPIDOGREL & ASPIRIN TAB 3X10''S(BGD-CLINICA)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('SF5', 'CLOPIDOGREL 75MG TAB 3X10''S(BGD-DMCH)', 'Tablet', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('N2U', 'COPAN 552C.80 FLOQ SWAB 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('SZ4', 'COPNAT N CREAM 15GM 1''S', 'Cream', '15GM', 'Renata All SKU and BRANDS.xls'),
  ('SZ5', 'COPNAT N OINTMENT 15GM 1''S', 'Medicine', '15GM', 'Renata All SKU and BRANDS.xls'),
  ('SG1', 'DABIREN 150MG CAP 2X6''S', 'Capsule', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('SF9', 'DABIREN 75MG CAP 2X6''S', 'Capsule', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('C3M', 'DDS KIT-MATERNAL AND CHILD HEALTH DRUGS (BGD-DGFP)', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C6C', 'DELTASONE 20MG TAB 5X10''S (BGD-LGI)', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('C5W', 'DENIXIL 0.5MG TAB 8X10''S (BGD-LGI)', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('SW6', 'DEPIAN 25MG TAB 3X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('CO5', 'DEROXIMEL DR 231MG CAP 5X6''S', 'Capsule', '231MG', 'Renata All SKU and BRANDS.xls'),
  ('ST9', 'DIAMPA FC 10MG TAB 2X10''S(BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N1X', 'DIAMPA FC 25MG TAB 1X10''S (BGD-LGI)', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('C6J', 'DIAMPA-M FC 500MG TAB 3X6''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('CH3', 'DIENOGEST 2MG TAB 1X10''S (BGD-CLINICA)', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('SU1', 'DOMIREN 60ML 5MG/5ML SUSP 1X1''S(BGD-LGI)', 'Suspension', '60ML, 5MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('SZ6', 'DOMPERIDONE 60ML (5MG/5ML) SUSP 1X1S (BGD-CLINICA)', 'Suspension', '60ML, 5MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('CX8', 'DOXICAP 100MG CAP 10X10''S (BGD-LGI)', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('CR1', 'DOXOFYLLINE FC 200MG TABS. 5X6S (BGD-CLINICA)', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('CT9', 'DUREVOLIS FC 10MG TAB 1X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CU1', 'DUREVOLIS FC 20MG TAB 1X4''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('CT8', 'DUREVOLIS FC 5MG TAB 2X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CX9', 'DYSMEN 500MG TAB 5X10''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SU2', 'E-GEL SG 200IU CAP 10X10''S (BGD-LGI)', 'Capsule', '200IU', 'Renata All SKU and BRANDS.xls'),
  ('C5K', 'EMEREN 50ML (4MG/5ML) SYRP 1X1''S (BGD-LGI)', 'Syrup', '50ML, 4MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('N4S', 'EMEREN FC 8MG TAB 3X10''S (BGD-DGDP)', 'Tablet', '8MG', 'Renata All SKU and BRANDS.xls'),
  ('N2C', 'EMEREN FC 8MG TAB 3X10''S (BGD-LGI)', 'Tablet', '8MG', 'Renata All SKU and BRANDS.xls'),
  ('C7U', 'EMEREN IM/IV 4ML(8MG/4ML) INJ 5X1''S (BGD-LGI)', 'Injection', '4ML, 8MG/4ML', 'Renata All SKU and BRANDS.xls'),
  ('SM2', 'ENTROVAS FC 24/26MG TAB 2X10''S', 'Tablet', '26MG', 'Renata All SKU and BRANDS.xls'),
  ('SM3', 'ENTROVAS FC 49/51MG TAB 2X10''S', 'Tablet', '51MG', 'Renata All SKU and BRANDS.xls'),
  ('SM4', 'ENTROVAS FC 97/103MG TAB 4X5''S', 'Tablet', '103MG', 'Renata All SKU and BRANDS.xls'),
  ('N1Z', 'EPICET FC 250MG TAB 2X10''S (BGD-LGI)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('C5L', 'EPICET FC 500MG TAB 1X10''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C6L', 'ESCILEX FC 10MG TAB 3X10''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CT2', 'ESCITALOPRAM OXALATE FC 5MG TAB 3X10''S (BGD-CLINICA)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('SY2', 'ESODIP 1.25MG TAB 2X10''S', 'Tablet', '1.25MG', 'Renata All SKU and BRANDS.xls'),
  ('SY3', 'ESODIP 2.50MG TAB 2X10''S', 'Tablet', '2.50MG', 'Renata All SKU and BRANDS.xls'),
  ('SY4', 'ESODIP 5MG TAB 2X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C8R', 'ESTELLIS FC TAB 1X28''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C4C', 'EVADOL FC 2MG TAB 3X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('C8S', 'EVATONE SG 1/100MG CAP 3X10''S', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('SM1', 'EXICOF 100ML SYRUP 1X1''S', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('C2E', 'EXTRACTION PLATE 2.0 ML 1X1S', 'Medicine', '2.0ML', 'Renata All SKU and BRANDS.xls'),
  ('SU3', 'FEBUREN FC 40GM TAB 3X10''S(BGD-LGI)', 'Tablet', '40GM', 'Renata All SKU and BRANDS.xls'),
  ('SX5', 'FEBUXOSTAT FC 40MG TAB 3X10''S(BGD-CLINICA)', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('C8O', 'FEELEX FC 100MG TAB 1X10''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C5X', 'FENADIN FC 120MG TAB 5X10''S (BGD-LGI)', 'Tablet', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('C5Y', 'FENADIN FC 180MG TAB 2X10''S (BGD-LGI)', 'Tablet', '180MG', 'Renata All SKU and BRANDS.xls'),
  ('N4H', 'FENTANYL CITRATE 2ML (100MCG/2ML) INJ 100X1''S', 'Injection', '2ML, 100MCG/2ML', 'Renata All SKU and BRANDS.xls'),
  ('CU4', 'FENTANYL CITRATE 2ML (100MCG/2ML) INJ 50X1''S (BGD-CLINICA)', 'Injection', '2ML, 100MCG/2ML', 'Renata All SKU and BRANDS.xls'),
  ('CT1', 'FENTANYL CITRATE 2ML (100MCG/2ML) INJ 50X1''S (BGD-DMCH)', 'Injection', '2ML, 100MCG/2ML', 'Renata All SKU and BRANDS.xls'),
  ('C1Q', 'FERIUM 10ML (500MG/10ML) INJ 1X1''S (BGD-LGI)', 'Injection', '10ML, 500MG/10ML', 'Renata All SKU and BRANDS.xls'),
  ('SD8', 'FERIUM 10ML INJ 1X1''S', 'Injection', '10ML', 'Renata All SKU and BRANDS.xls'),
  ('N3Q', 'FERRIC CARBOXYMALTOSE 10ML (500MG/10ML) INJ 100X1''S', 'Injection', '10ML, 500MG/10ML', 'Renata All SKU and BRANDS.xls'),
  ('C7P', 'FEXOFENADIN HCL 30ML (30MG/5ML) SUSP 1X1''S(BGD-CLINICA)', 'Suspension', '30ML, 30MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('SN3', 'FEXOFENADINE HCL FC 120MG TAB 5X10''S(BGD-CLINICA)', 'Tablet', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('SU5', 'FLONTIN FC 500MG TAB 3X10''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C2W', 'FOLIGEST 75 IU INJ 1X1''S', 'Injection', '75IU', 'Renata All SKU and BRANDS.xls'),
  ('CO4', 'FOLINIC FC 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('SZ3', 'FUNGIROX 15G CREAM 1X1''S', 'Cream', '15G', 'Renata All SKU and BRANDS.xls'),
  ('N1W', 'FUROCLAV FC 500MG TAB 2X7''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C6H', 'GABA - P 50MG CAP 3X10''S (BGD-LGI)', 'Capsule', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('CY5', 'GABA 300MG TAB 3X10''S (BGD-LGI)', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('N1U', 'GABA-P 25MG CAP 5X6''S (BGD-LGI)', 'Capsule', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('SG8', 'GABA-P 75MG CAP 3X10''S(BGD-DMCH)', 'Capsule', '75MG', 'Renata All SKU and BRANDS.xls'),
  ('N5Z', 'GAVISTOP 200ML SUSP 1X1''S', 'Suspension', '200ML', 'Renata All SKU and BRANDS.xls'),
  ('S66', 'GLERON FC 90MG TAB 1X10''S', 'Tablet', '90MG', 'Renata All SKU and BRANDS.xls'),
  ('SX6', 'GLICLAZIDE 80MG TAB 3X10S (BGD-CLINICA)', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('CI9', 'GLINTA FC 5MG TAB 3X10''S (BGD-LGI)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C6N', 'GLINTA-M FC 500MG TAB 3X10''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C4W', 'HEXPARK 2MG TAB 5X10''S', 'Tablet', '2MG', 'Renata All SKU and BRANDS.xls'),
  ('C4X', 'HEXPARK 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CS1', 'INDAREN-G RENACAP DPI CAP 3X10''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('N2H', 'INDULA 25MCG TAB 3X10''S', 'Tablet', '25MCG', 'Renata All SKU and BRANDS.xls'),
  ('N3N', 'IPAS MVA PLUS? ASPIRATOR W/2ML TUBE OF SILICONE 1X1''S', 'Medicine', '2ML', 'Renata All SKU and BRANDS.xls'),
  ('N4G', 'JAKRIF FC 5MG TAB 1X14''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('N1S', 'JEEBEE 60MG CAP 5X6''S (BGD-LGI)', 'Capsule', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('N3Y', 'KETOROLAC TROMETHAMINE IM/IV 1ML (30MG/ML) INJ 500X1''S(BGD)', 'Injection', '1ML, 30MG', 'Renata All SKU and BRANDS.xls'),
  ('C2L', 'KIT CERVICAL COLLECTION BRUSH (BULK) 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C2B', 'KIT COBAS 4800 HPV AMP DET 960T IVD 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N2P', 'KIT COBAS 4800 HPV AMP/DET 240T CE-IVD 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C2K', 'KIT COBAS 4800 HPV CONTROLS 10 SETS IVD 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C2I', 'KIT COBAS 4800 SYS LIQ CYT PREP HPV 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N2O', 'KIT COBAS 4800 SYS LIQ. CYT 240T IVD 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N2M', 'KIT COBAS 4800 SYS SAMPLE PREP 240T IVD 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C2J', 'KIT COBAS 4800 SYS SAMPLE PREPARATION 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N2N', 'KIT COBAS 4800 SYS WASH BUFFER 240T IVD 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C2H', 'KIT COBAS 4800 SYS WASH BUFFER HPV CT/NG 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N2R', 'KIT COBAS PCR MEDIA SECONDARY TUBE 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N2S', 'KIT COBAS PCR MEDIA TUBE REPLACEMENT CAP 1X1''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('C2M', 'KIT ROCHE CELL COLLECTION MEDIUM 20 ML 1X1''S', 'Medicine', '20ML', 'Renata All SKU and BRANDS.xls'),
  ('SB9', 'LAXANA SG 24MCG CAP 2X10''S', 'Capsule', '24MCG', 'Renata All SKU and BRANDS.xls'),
  ('SC1', 'LAXANA SG 8MCG CAP 3X10''S', 'Capsule', '8MCG', 'Renata All SKU and BRANDS.xls'),
  ('N4P', 'LEVETIRACETAM 5ML 500MG/5ML INJ 200X1''S(BGD-CLINICA)', 'Injection', '5ML, 500MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('C7J', 'LEVETIRACETAM FC 250MG TAB 2X10''S (BGD-CLINICA)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('CT3', 'LEVETIRACETAM FC 500MG TAB 1X10''S(BGD-CLINICA)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N1O', 'LEVOFLOXACIN 250MG TAB 10X10''S (BGD-TBH)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('CT7', 'LEVOFLOXACIN 500MG TAB 5X6''S (BGD-CLINICA)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SN6', 'LEVOTHYROXINE SODIUM 50MCG TAB 3X30''S(BGD-CLINICA)', 'Tablet', '50MCG', 'Renata All SKU and BRANDS.xls'),
  ('C6A', 'LINAGLIPTIN FC 5MG TAB 3X10''S (BGD-CLINICA)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('107', 'LINEZ 400MG TAB 2X6''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('108', 'LINEZ 600MG TAB 2X6''S', 'Tablet', '600MG', 'Renata All SKU and BRANDS.xls'),
  ('C6O', 'LINEZ 600MG TAB 2X6''S (BGD-LGI)', 'Tablet', '600MG', 'Renata All SKU and BRANDS.xls'),
  ('CV2', 'LINEZOLID 600MG TAB 2X6''S (BGD-CLINICA)', 'Tablet', '600MG', 'Renata All SKU and BRANDS.xls'),
  ('SN4', 'LOSARTAN POTASSIUM 50MG TAB 5X10''S(BGD-CLINICA)', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('C9Z', 'LUBIPROSTONE SG 8MCG CAP 3X10''S(BGD-CLINICA)', 'Capsule', '8MCG', 'Renata All SKU and BRANDS.xls'),
  ('SU7', 'LUCAN-R 150MG CAP 2X6''S (BGD-LGI)', 'Capsule', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('C6G', 'LUCENT SG 0.25MCG CAP 3X10''S (BGD-LGI)', 'Capsule', '0.25MCG', 'Renata All SKU and BRANDS.xls'),
  ('C3Y', 'LULIREN 10G (1%) CREAM 1X1''S', 'Cream', '10G', 'Renata All SKU and BRANDS.xls'),
  ('C3Z', 'LULIREN 20G (1%) CREAM 1X1''S', 'Cream', '20G', 'Renata All SKU and BRANDS.xls'),
  ('C9L', 'LULIREN 30G (1%) CREAM 1X1''S', 'Cream', '30G', 'Renata All SKU and BRANDS.xls'),
  ('CP3', 'LURA FC 120MG TAB 2X6''S', 'Tablet', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('CO8', 'LURA FC 20MG TAB 2X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('CO9', 'LURA FC 40MG TAB 1X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('CP1', 'LURA FC 60MG TAB 1X10''S', 'Tablet', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('CP2', 'LURA FC 80MG TAB 1X10''S', 'Tablet', '80MG', 'Renata All SKU and BRANDS.xls'),
  ('N5W', 'MAGMAX FC 365MG TAB 10X6''S', 'Tablet', '365MG', 'Renata All SKU and BRANDS.xls'),
  ('CW8', 'MAGNESIUM SULPHATE 5ML(2.50G/5ML) INJ 1X5''S(BGD-CLINICA)', 'Injection', '5ML, 2.50G/5ML', 'Renata All SKU and BRANDS.xls'),
  ('945', 'MAGSUM 5ML INJ 1X5''S', 'Injection', '5ML', 'Renata All SKU and BRANDS.xls'),
  ('N4F', 'MALE LATEX CONDOM 1X1''S (BGD-STC)', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('SE5', 'MALE LATEX CONDOM 48X3''S(BGD-ICDDRB)', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('S19', 'MARIPRIST 1X5''S (BGD-MRISTPS)', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C3G', 'MATRIKONA TAB 3X10''S (BGD-THP)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C9N', 'MAXOLAX FC 10MG TAB 3X10''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('842', 'MEF-Q TAB 250MG 1X100''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('C8A', 'MENOFIN 75 INJ 1''S', 'Injection', '', 'Renata All SKU and BRANDS.xls'),
  ('C6U', 'MEROPEN IV 1G INJ 1X1''S (BGD-LGI)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('C8D', 'MEROPENEM IV 1G INJ. 100X1S (BGD-CLINICA)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('CF8', 'MEROPENEM IV 500MG INJ 50X1S (BGD-CLINICA)', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('S97', 'METIROX 10MG TAB 5X14''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('S96', 'METIROX 5MG TAB 3X30''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('089', 'MEZ IV INJ 100ML', 'Injection', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('SK7', 'MICROGEST SG 200MG CAP 3X10''S (BGD-LGI)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('N4I', 'MIDAZOLAM HCL IM/IV 3ML (15MG/3ML) INJ 100X1''S', 'Injection', '3ML, 15MG/3ML', 'Renata All SKU and BRANDS.xls'),
  ('AB5', 'MIDAZOLAM HCL IM/IV 3ML (15MG/3ML) INJ 1X1''S', 'Injection', '3ML, 15MG/3ML', 'Renata All SKU and BRANDS.xls'),
  ('CX1', 'MIDAZOLAM HCL IM/IV 3ML (15MG/3ML) INJ 50X1''S(BGD-CLINICA)', 'Injection', '3ML, 15MG/3ML', 'Renata All SKU and BRANDS.xls'),
  ('CE7', 'MIDAZOLAM HCL IM/IV 3ML INJ 50X1''S(BGD-DMCH)', 'Injection', '3ML', 'Renata All SKU and BRANDS.xls'),
  ('993', 'MIDZO 7.5MG TAB 3X10''S', 'Tablet', '7.5MG', 'Renata All SKU and BRANDS.xls'),
  ('992', 'MIDZO IV/IM 15MG/3ML INJ 1''S', 'Injection', '15MG/3ML', 'Renata All SKU and BRANDS.xls'),
  ('S55', 'MIGESIC 200MG TAB 3X10''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C6Z', 'MIROTIV FC 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C7A', 'MIROTIV FC 15MG TAB 3X10''S', 'Tablet', '15MG', 'Renata All SKU and BRANDS.xls'),
  ('C6X', 'MIROTIV FC 2.5MG TAB 3X10''S', 'Tablet', '2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C6Y', 'MIROTIV FC 5MG TAB 3X10''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C2S', 'MITADIP FC 15MG TAB 3X10''S', 'Tablet', '15MG', 'Renata All SKU and BRANDS.xls'),
  ('C2T', 'MITADIP FC 30MG TAB 3X10''S', 'Tablet', '30MG', 'Renata All SKU and BRANDS.xls'),
  ('C2R', 'MITADIP FC 7.5MG TAB 3X10''S', 'Tablet', '7.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C2P', 'MOXIFLOXACIN HYDROCHLORIDE FC 400MG TAB 2X6''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('CQ2', 'MULTIPLE MICRONUTRIENT SUPL TAB 3X10''S(BGD-JVTA)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('N2Z', 'MUPITOP (2%) 10G OINT 1X1''S', 'Cream', '10G', 'Renata All SKU and BRANDS.xls'),
  ('C2F', 'MWP MICRO WELL PLATE AD-PLATE 0.3 ML 1X1''S', 'Medicine', '0.3ML', 'Renata All SKU and BRANDS.xls'),
  ('CD8', 'MYCOPHENOLET MOFETIL TAB 3X10S (BGD-CLINICA)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('CB4', 'MYOSIT FC 750MG TAB 5X6''S', 'Tablet', '750MG', 'Renata All SKU and BRANDS.xls'),
  ('N2J', 'MYOSIT PLUS FC TAB 5X6''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('SJ5', 'NEUROBEST TAB 6X10''S (BGD-LGI)', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('SA4', 'NEXDEX 30MG CAP 6X10''S', 'Capsule', '30MG', 'Renata All SKU and BRANDS.xls'),
  ('SA1', 'NEXDEX 60MG CAP 5X6''S', 'Capsule', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('SB3', 'NEXOLID FC 200MG TAB 1X6''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('N2B', 'NITROREN SR 2.6MG TAB 3X10''S (BGD-LGI)', 'Tablet', '2.6MG', 'Renata All SKU and BRANDS.xls'),
  ('AC5', 'NORETHISTERONE 5MG TAB 10X10S (BGD-GOVT)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CD9', 'NORETHISTERONE ACETATE 5MG TAB 10X10''S(BGD-CLINICA)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('CY8', 'NORMANAL 500MG TAB 3X10''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N4D', 'NORMANAL DS 1000MG TAB 5X6''S', 'Tablet', '1000MG', 'Renata All SKU and BRANDS.xls'),
  ('ST4', 'NOVELIP 180MG TAB 2X5''S', 'Tablet', '180MG', 'Renata All SKU and BRANDS.xls'),
  ('C5N', 'ODMON 10MG TAB 3X10''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CA4', 'OMEPRAZOLE 20MG CAP 5X4''S(BGD-CLINICA)', 'Capsule', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('CV3', 'ONDANSETRON HCL 50ML (4MG/5ML) SYRP 1X1''S(BGD-CLINICA)', 'Syrup', '50ML, 4MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('CC2', 'ONDANSETRON HCL FC 8MG TAB 3X10''S (BGD-CLINICA)', 'Tablet', '8MG', 'Renata All SKU and BRANDS.xls'),
  ('N4C', 'OPEXA 60ML (2.5MG/ML) OSLUSN 1X1''S', 'Medicine', '60ML, 2.5MG', 'Renata All SKU and BRANDS.xls'),
  ('S95', 'OPEXA FC 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('N4B', 'OPEXA ODT 10MG TAB 3X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('SW1', 'ORAGON FC 150MG TAB 2X6''S', 'Tablet', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('N2G', 'ORCEF 200MG CAP 2X8''S (BGD-LGI)', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('CB1', 'OXCARB XR 150MG TAB 5X10''S', 'Tablet', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('CB2', 'OXCARB XR 300MG TAB 8X6''S', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('CB3', 'OXCARB XR 600MG TAB 5X6''S', 'Tablet', '600MG', 'Renata All SKU and BRANDS.xls'),
  ('C9S', 'PALONOSETRON HCL 5ML (0.25MG/5ML) INJ 1X5''S (BGD-NICRH)', 'Injection', '5ML, 0.25MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('CU7', 'PALONOSETRON HCL 5ML (0.25MG/5ML) INJ 50X1''S (BGD-CLINICA)', 'Injection', '5ML, 0.25MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('C7O', 'PALONOSETRON HCL FC 0.5MG TAB 2X10''S(BGD-CLINICA)', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('C8P', 'PANTOPRAZOLE SODIUM 20MG TAB 5X10''S(BGD-CLINICA)', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('SQ8', 'PIPERACILLIN & TAZOBACTAM IV 4.50G INF 1X1''S(BGD-CLINICA)', 'Injection', '4.50G', 'Renata All SKU and BRANDS.xls'),
  ('CE8', 'PIPERACILLIN & TAZOBACTAM IV 4.50G INF 25X1''S', 'Injection', '4.50G', 'Renata All SKU and BRANDS.xls'),
  ('CU8', 'PIPERACILLIN AND TAZOBACTAM IV 4.50G INF 25X1''S', 'Injection', '4.50G', 'Renata All SKU and BRANDS.xls'),
  ('CG6', 'PIRFEDONE 267MG TAB 5X6''S', 'Tablet', '267MG', 'Renata All SKU and BRANDS.xls'),
  ('CG7', 'PIRFEDONE 534MG TAB 3X6''S', 'Tablet', '534MG', 'Renata All SKU and BRANDS.xls'),
  ('CG8', 'PIRFEDONE 801MG TAB 2X6''S', 'Tablet', '801MG', 'Renata All SKU and BRANDS.xls'),
  ('N2T', 'PLASTIC CHUTE 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('132', 'POLYCEF 250MG CAP (5X4''S)', 'Capsule', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('930', 'POLYCEF 500MG CAP (7X4''S)', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('137', 'POLYCEF PAEDIATRIC DROPS 15ML', 'Drops', '15ML', 'Renata All SKU and BRANDS.xls'),
  ('138', 'POLYCEF SUSPENSION 100ML', 'Suspension', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('225', 'POLYCEF SUSPENSION DS 100ML', 'Suspension', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('N1T', 'PRAZOLE 20MG CAP 5X14''S (BGD-LGI)', 'Capsule', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('SO1', 'PREGABALIN 25MG CAP 5X6''S(BGD-CLINICA)', 'Capsule', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('CA5', 'PREGABLIN 50MG CAP 3X10''S(BGD-CLINICA)', 'Capsule', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('N6I', 'PREGMOS DR 10MG TAB 5X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N1R', 'PRIMAVERA SG 500MG CAP 3X10''S (BGD-LGI)', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C2X', 'PROLIFIC 5000 IU INJ 1X1''S', 'Injection', '5000IU', 'Renata All SKU and BRANDS.xls'),
  ('C8W', 'PROSTON 0.5MG/3G CERVICAL GEL 1X1''S', 'Cream', '0.5MG/3G', 'Renata All SKU and BRANDS.xls'),
  ('SA7', 'PTU 50MG TAB 4X14''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SI5', 'PULMINO FC 200MG TABS 5X6''S(BGD-LGI)', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C19', 'PUSHTIKONA-5 PWD 10X3''S (BGD-WVB)', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('259', 'PYRA PLUS (15X10''S)', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C2C', 'REAGENT RESERVOIR 200 ML 1X1S', 'Medicine', '200ML', 'Renata All SKU and BRANDS.xls'),
  ('C2D', 'REAGENT RESERVOIR 50 ML 1X1''S', 'Medicine', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('SV2', 'RECOF 100ML 15MG/5ML SYRP 1X1''S(BGD-LGI)', 'Syrup', '100ML, 15MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('SA3', 'REDUCOF 100ML SYRP 1X1''S', 'Syrup', '100ML', 'Renata All SKU and BRANDS.xls'),
  ('CF4', 'RELUREN TAB 2X5''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('C9W', 'RENABEC-FG HFA (120PUFF) MDI 1X1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('C8K', 'RENAFOR-B HFA 4.5/160MCG (120PUFF) MDI 1X1''S', 'Medicine', '160MCG', 'Renata All SKU and BRANDS.xls'),
  ('C8J', 'RENAFOR-B HFA 4.5/80MCG (120PUFF) MDI 1X1''S', 'Medicine', '80MCG', 'Renata All SKU and BRANDS.xls'),
  ('C7G', 'RENAFOR-B RENACAP 12/400MCG (DPI) 3X10''S', 'Medicine', '400MCG', 'Renata All SKU and BRANDS.xls'),
  ('C7E', 'RENAFOR-B RENACAP 6/100MCG (DPI) 3X10''S', 'Medicine', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('C7F', 'RENAFOR-B RENACAP 6/200MCG (DPI) 3X10''S', 'Medicine', '200MCG', 'Renata All SKU and BRANDS.xls'),
  ('N1B', 'RENAFOR-G HFA 4.8/9MCG (120PUFF) 1X1''S', 'Medicine', '9MCG', 'Renata All SKU and BRANDS.xls'),
  ('CR4', 'RENAHALER (DPI DEVICE) 1''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('SG3', 'RENAPINE 100MG TAB 8X6''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('SG2', 'RENAPINE 25MG TAB 5X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('ST3', 'RENAPINE XR 200MG TAB 3X10''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('CF3', 'RENAPINE XR 300MG TAB 5X6''S', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('ST2', 'RENAPINE XR 50MG TAB 5X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('C1U', 'RENAPINE XR 50MG TAB 5X10''S (BGD-LGI)', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SY1', 'RENASONE 10G CREAM 1X1''S', 'Cream', '10G', 'Renata All SKU and BRANDS.xls'),
  ('SI7', 'REZOR FC 40MG TAB 3X10''S (BDG-LGI)', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('CF2', 'RILUZOL FC 50MG TAB 2X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('SA5', 'RIVAREN 1.5MG CAP 3X6''S', 'Capsule', '1.5MG', 'Renata All SKU and BRANDS.xls'),
  ('SA6', 'RIVAREN 3MG CAP 2X6''S', 'Capsule', '3MG', 'Renata All SKU and BRANDS.xls'),
  ('C6M', 'ROLAC 10MG TAB 4X14''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C6D', 'ROLIP FC 10MG TAB 3X10''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N2E', 'ROLIP FC 5MG TAB 3X10''S (BGD-LGI)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C8Q', 'ROSUVASTATIN CALCIUM FC 5MG TAB 3X10''S(BGD-CLINICA)', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('SP1', 'ROSUVASTATIN FC 10MG TAB 3X10''S(BGD-CLINICA)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('S67', 'ROXOLYTE 10MG TAB 1X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('SI9', 'SALINE-R 10.25G ORS 1X20''S(BGD-LGI)', 'Medicine', '10.25G', 'Renata All SKU and BRANDS.xls'),
  ('902', 'SALINE-R 20''S', 'Medicine', '', 'Renata All SKU and BRANDS.xls'),
  ('N5D', 'SUBAZOL 65MG CAP 5X6''S', 'Capsule', '65MG', 'Renata All SKU and BRANDS.xls'),
  ('C8F', 'SUPADOPA TR 145MG CAP 3X6''S', 'Capsule', '145MG', 'Renata All SKU and BRANDS.xls'),
  ('C8G', 'SUPADOPA TR 195MG CAP 3X6''S', 'Capsule', '195MG', 'Renata All SKU and BRANDS.xls'),
  ('C8H', 'SUPADOPA TR 245MG CAP 2X6''S', 'Capsule', '245MG', 'Renata All SKU and BRANDS.xls'),
  ('C8E', 'SUPADOPA TR 95MG CAP 5X6''S', 'Capsule', '95MG', 'Renata All SKU and BRANDS.xls'),
  ('C7Y', 'TAPAZOL 10MG TAB 5X14''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C7Z', 'TAPAZOL 5MG TAB 3X30''S', 'Tablet', '5MG', 'Renata All SKU and BRANDS.xls'),
  ('C5S', 'TAVEN 10MG TAB 3X10''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('C5T', 'TAVEN 20MG TAB 3X10''S (BGD-LGI)', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('SK3', 'THYROX 50MCG TAB 3X30''S (BGD-LGI)', 'Tablet', '50MCG', 'Renata All SKU and BRANDS.xls'),
  ('AB1', 'THYROX 50MCG TAB 3X30''S(BGD-DMCH)', 'Tablet', '50MCG', 'Renata All SKU and BRANDS.xls'),
  ('SW3', 'TIEMONIUM METHYL SULP 50MG TAB 10X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('N4J', 'TIEMONIUM METHYL SULPHATE 2ML (5MG/2ML) INJ 100X1''S', 'Injection', '2ML, 5MG/2ML', 'Renata All SKU and BRANDS.xls'),
  ('N1Y', 'TIGOVER FC 10MG TAB 5X10''S (BGD-LGI)', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CR7', 'TIOREN RENACAP 18MCG (DPI) CAP 3X10''S', 'Capsule', '18MCG', 'Renata All SKU and BRANDS.xls'),
  ('C2G', 'TIP HIGH VOL 1 ML WITH FILTER 1X1''S', 'Medicine', '1ML', 'Renata All SKU and BRANDS.xls'),
  ('N4K', 'TRANEXAMIC 5ML (500MG/5ML) INJ 100X1''S', 'Injection', '5ML, 500MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('SW8', 'TRANEXAMIC 5ML 500MG/5ML INJ 50X1''S(BGD-CLINICA)', 'Injection', '5ML, 500MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('CA8', 'TRANEXAMIC ACID 500MG CAP 2X10''S', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N21', 'TRITIN 100MG TAB 3X10''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C4P', 'ULFIX 200ML (1G/5ML) SUSP 1X1''S', 'Suspension', '200ML, 1G/5ML', 'Renata All SKU and BRANDS.xls'),
  ('C4R', 'ULFIX FC 1000MG TAB 10X6''S', 'Tablet', '1000MG', 'Renata All SKU and BRANDS.xls'),
  ('C4Q', 'ULFIX FC 500MG TAB 10X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('CM2', 'UPAREN-15 TAB 2X6''S', 'Tablet', '', 'Renata All SKU and BRANDS.xls'),
  ('N2F', 'URITONE 20MG TAB 3X10''S (BGD-LGI)', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('SD6', 'URSOREN FC 150MG TAB 3X10''S', 'Tablet', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('SD7', 'URSOREN FC 300MG TAB 5X6''S', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('C9G', 'URSOREN FC 300MG TAB 5X6''S (BGD-LGI)', 'Tablet', '300MG', 'Renata All SKU and BRANDS.xls'),
  ('C9F', 'V CAP SG CAP 1X6''S (BGD-LGI)', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('N1A', 'VALPORIN SG 250MG CAP 5X10''S', 'Capsule', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('N4R', 'VANCOMYCIN HCL IV 1G INF 100X1''S (BGD-CLINICA)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('C2Q', 'VANCOMYCIN HCL IV 1G INF 50X1''S (BGD-CLINICA)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('SV6', 'VANCOMYCIN HCL IV 1G INF 50X1''S(BGD-DMCH)', 'Injection', '1G', 'Renata All SKU and BRANDS.xls'),
  ('CV6', 'VANCOMYCIN HCL IV 500MG INF 50X1''S (BGD-CLINICA)', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('643', 'VCAP SOFT GELATIN CAP 1X6''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('CJ3', 'VILAZON FC 10MG TAB 2X10''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('CJ4', 'VILAZON FC 20MG TAB 2X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('CJ5', 'VILAZON FC 40MG TAB 2X10''S', 'Tablet', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('CS2', 'VILDIUM RENACAP DPI CAP 3X10''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('CS3', 'VILTICA RENACAP 25/100MCG DPI CAP 3X10''S', 'Capsule', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('CS4', 'VILTICA RENACAP 25/100MCG DPI CAP 6X10''S', 'Capsule', '100MCG', 'Renata All SKU and BRANDS.xls'),
  ('CS5', 'VILTICA RENACAP 25/200MCG DPI CAP 3X10''S', 'Capsule', '200MCG', 'Renata All SKU and BRANDS.xls'),
  ('CS6', 'VILTICA RENACAP 25/200MCG DPI CAP 6X10''S', 'Capsule', '200MCG', 'Renata All SKU and BRANDS.xls'),
  ('CR8', 'VILTICA-U RENACAP DPI CAP 1X10''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('CR9', 'VILTICA-U RENACAP DPI CAP 3X10''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('C9H', 'VITA-D3 1000 IU TAB 3X10''S (BGD-LGI)', 'Tablet', '1000IU', 'Renata All SKU and BRANDS.xls'),
  ('C5P', 'VITA-D3 40000 IU CAP 2X5''S (BGD-LGI)', 'Capsule', '40000IU', 'Renata All SKU and BRANDS.xls'),
  ('S06', 'VITAMIN-A SG 100000 IU CAP 500X1''S (BGD-CMSD)', 'Capsule', '100000IU', 'Renata All SKU and BRANDS.xls'),
  ('C58', 'VITAMIN-A SG 200000 IU CAP 500X1''S (BGD-CMSD)', 'Capsule', '200000IU', 'Renata All SKU and BRANDS.xls'),
  ('C9I', 'VOMIREN 5ML (0.25MG/5ML) INJ 1X5''S (BGD-LGI)', 'Injection', '5ML, 0.25MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('N2D', 'VOMIREN FC 0.5MG TAB 2X10''S (BGD-LGI)', 'Tablet', '0.5MG', 'Renata All SKU and BRANDS.xls'),
  ('N1N', 'VOXAMIN FC 100MG TAB 5X6''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('CI8', 'VOXAMIN FC 50MG TAB 3X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('CK8', 'VOXAMIN XR 100MG CAP 3X6''S', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('CK9', 'VOXAMIN XR 150MG CAP 3X6''S', 'Capsule', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('SH5', 'XIOMOX FC 400MG TAB 2X6''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('N2A', 'XIOMOX FC 400MG TAB 2X6''S (BGD-LGI)', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('C5Q', 'ZITHRIN 35ML (200MG/5ML) DSYRP 1X1''S (BGD-LGI)', 'Medicine', '35ML, 200MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('C5U', 'ZITHRIN FC 500MG TAB 3X5''S (BGD-LGI)', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('CJ6', '5HTP 100MG CAP 5X6''S', 'Capsule', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('T47', 'ALIKSIR EC SG CAP 3X10''S', 'Capsule', '', 'Renata All SKU and BRANDS.xls'),
  ('T69', 'BLISS 140MG CAP 5X6''S (MILK THISTLE)', 'Capsule', '140MG', 'Renata All SKU and BRANDS.xls'),
  ('SI2', 'GARLLIUM 385MG CAP 5X6''S', 'Capsule', '385MG', 'Renata All SKU and BRANDS.xls'),
  ('T37', 'GINERA 500MG VEG CAP 5X6''S', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('TE3', 'JEEBEE 120MG CAP 5X6''S', 'Capsule', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('T48', 'JEEBEE 60MG VEG CAP 5X6''S', 'Capsule', '60MG', 'Renata All SKU and BRANDS.xls'),
  ('T23', 'LACTOHIL 100G 1''S', 'Medicine', '100G', 'Renata All SKU and BRANDS.xls'),
  ('S40', 'NUTRILINA 500MG VEG CAP 10X6''S', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('N5C', 'PREGCARE 5G PWDR 25X1S', 'Medicine', '5G', 'Renata All SKU and BRANDS.xls'),
  ('T35', 'PREGCARE 5G SACHET 25X1''S', 'Sachet', '5G', 'Renata All SKU and BRANDS.xls'),
  ('T83', 'PRIMAVERA SG 1000MG CAP 6X5''S', 'Capsule', '1000MG', 'Renata All SKU and BRANDS.xls'),
  ('T38', 'PRIMAVERA SG 500MG CAP 3X10''S', 'Capsule', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('T68', 'SCARLET 430MG VEG CAP 5X6''S', 'Capsule', '430MG', 'Renata All SKU and BRANDS.xls'),
  ('C3K', 'ANAYA FC 1MG TAB 3X10''S', 'Tablet', '1MG', 'Renata All SKU and BRANDS.xls'),
  ('CH1', 'APEMEG 160MG TAB 2X6''S', 'Tablet', '160MG', 'Renata All SKU and BRANDS.xls'),
  ('N2V', 'APEMEG 160MG TAB 3X5''S', 'Tablet', '160MG', 'Renata All SKU and BRANDS.xls'),
  ('N1J', 'CAPAREN FC 500MG TAB 2X7''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SV9', 'CAPAREN FC 500MG TAB 4X6''S', 'Tablet', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('SI3', 'CARMUSTINE 100MG INJ 1X1''S', 'Injection', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C9J', 'CYBINE 100MG INJ 1X1''S', 'Injection', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C9K', 'CYBINE 500MG INJ 1X1''S', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('C8U', 'DASAREN 100MG TAB 2X5''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C8T', 'DASAREN 140MG TAB 2X5''S', 'Tablet', '140MG', 'Renata All SKU and BRANDS.xls'),
  ('X03', 'ERLOREN 100MG TAB 1X7''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('X04', 'ERLOREN 150MG TAB 1X7''S', 'Tablet', '150MG', 'Renata All SKU and BRANDS.xls'),
  ('N4Z', 'FOLINIC 10ML (100MG/10ML) INJ 1X1''S', 'Injection', '10ML, 100MG/10ML', 'Renata All SKU and BRANDS.xls'),
  ('N4Y', 'FOLINIC 5ML (50MG/5ML) INJ 1X1''S', 'Injection', '5ML, 50MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('SG9', 'GEFIREN FC 250MG TAB 2X6''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('C9B', 'GEMCIT 1000MG INJ 1X1''S', 'Injection', '1000MG', 'Renata All SKU and BRANDS.xls'),
  ('C9A', 'GEMCIT 200MG INJ 1X1''S', 'Injection', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C3D', 'IRINACAN 100MG INJ 1X1''S', 'Injection', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C3C', 'IRINACAN 40MG INJ 1X1''S', 'Injection', '40MG', 'Renata All SKU and BRANDS.xls'),
  ('X12', 'LAPAREN 250MG TAB 1X10''S', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('N2X', 'LEDOMIDE 10MG CAP 1X7''S', 'Capsule', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('X09', 'LEDOMIDE 10MG CAP 2X6''S', 'Capsule', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N2W', 'LEDOMIDE 25MG CAP 1X7''S', 'Capsule', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('X10', 'LEDOMIDE 25MG CAP 2X6''S', 'Capsule', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('X14', 'MELPHALAN 50MG INJ 1X1''S', 'Injection', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('C4S', 'METORAX 2ML INJ 1X1''S', 'Injection', '2ML', 'Renata All SKU and BRANDS.xls'),
  ('X13', 'NILOREN 200MG CAP 2X6''S', 'Capsule', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C9T', 'OVARIB FC 100MG TAB 2X6''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('CH2', 'PAZOREN FC 200MG TAB 2X6''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('C4A', 'PEMEXEN 100MG INJ 1X1''S', 'Injection', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('C4B', 'PEMEXEN 500MG INJ 1X1''S', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('622', 'PROSCAN 250MG TAB (3X10''S)', 'Tablet', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('SZ1', 'RELUPROS 120MG TAB 5X6''S', 'Tablet', '120MG', 'Renata All SKU and BRANDS.xls'),
  ('N6G', 'RENACARB 15ML (150MG/15ML) INJ 1X1''S', 'Injection', '15ML, 150MG/15ML', 'Renata All SKU and BRANDS.xls'),
  ('N6H', 'RENACARB 45ML (450MG/45ML) INJ 1X1''S', 'Injection', '45ML, 450MG/45ML', 'Renata All SKU and BRANDS.xls'),
  ('C9U', 'RENAPLAT 10ML INJ 1X1''S', 'Injection', '10ML', 'Renata All SKU and BRANDS.xls'),
  ('C9V', 'RENAPLAT 50ML INJ 1X1''S', 'Injection', '50ML', 'Renata All SKU and BRANDS.xls'),
  ('C6V', 'RENOXTIN 10ML (50MG/10ML) INJ 1X1''S', 'Injection', '10ML, 50MG/10ML', 'Renata All SKU and BRANDS.xls'),
  ('C6W', 'RENOXTIN 20ML (100MG/20ML) INJ 1X1''S', 'Injection', '20ML, 100MG/20ML', 'Renata All SKU and BRANDS.xls'),
  ('C3F', 'R-FU 250MG DS INJ 1X1''S', 'Injection', '250MG', 'Renata All SKU and BRANDS.xls'),
  ('C4V', 'R-FU 500MG DS INJ 1X1''S', 'Injection', '500MG', 'Renata All SKU and BRANDS.xls'),
  ('CB5', 'R-PAG FC 12.5MG TAB 1X10''S', 'Tablet', '12.5MG', 'Renata All SKU and BRANDS.xls'),
  ('CV8', 'R-PAG FC 12.5MG TAB 1X7''S', 'Tablet', '12.5MG', 'Renata All SKU and BRANDS.xls'),
  ('CB6', 'R-PAG FC 25MG TAB 1X10''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('CV9', 'R-PAG FC 25MG TAB 1X7''S', 'Tablet', '25MG', 'Renata All SKU and BRANDS.xls'),
  ('CB7', 'R-PAG FC 50MG TAB 1X10''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('CW1', 'R-PAG FC 50MG TAB 1X7''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls'),
  ('X01', 'SOFENIB 200MG TAB 3X4''S', 'Tablet', '200MG', 'Renata All SKU and BRANDS.xls'),
  ('CW2', 'TAMIREN FC 20MG TAB 3X10''S', 'Tablet', '20MG', 'Renata All SKU and BRANDS.xls'),
  ('C3L', 'TAXODOC 2ML (20MG/ML) INJ 1X1''S', 'Injection', '2ML, 20MG', 'Renata All SKU and BRANDS.xls'),
  ('C3E', 'TAXODOC 4ML (80MG/4ML) INJ 1X1''S', 'Injection', '4ML, 80MG/4ML', 'Renata All SKU and BRANDS.xls'),
  ('C3J', 'TAXOPAC 20ML (100MG/16.7ML) INJ 1X1''S', 'Injection', '20ML, 100MG/16.7ML', 'Renata All SKU and BRANDS.xls'),
  ('C3B', 'TAXOPAC 50ML (300MG/50ML) INJ 1X1''S', 'Injection', '50ML, 300MG/50ML', 'Renata All SKU and BRANDS.xls'),
  ('C3I', 'TAXOPAC 5ML (30MG/5ML) INJ 1X1''S', 'Injection', '5ML, 30MG/5ML', 'Renata All SKU and BRANDS.xls'),
  ('N1E', 'TECAN 4ML (4MG/4ML) LYOPHILIZED INJ 1X1''S', 'Injection', '4ML, 4MG/4ML', 'Renata All SKU and BRANDS.xls'),
  ('X02', 'TYROKIN 400MG TAB 1X10''S', 'Tablet', '400MG', 'Renata All SKU and BRANDS.xls'),
  ('X08', 'TYROKIN FC 100MG TAB 1X10''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('N1D', 'VENCLAXTA FC 100MG TAB 1X10''S', 'Tablet', '100MG', 'Renata All SKU and BRANDS.xls'),
  ('N1M', 'VENCLAXTA FC 10MG TAB 1X7''S', 'Tablet', '10MG', 'Renata All SKU and BRANDS.xls'),
  ('N1C', 'VENCLAXTA FC 50MG TAB 2X5''S', 'Tablet', '50MG', 'Renata All SKU and BRANDS.xls')
ON DUPLICATE KEY UPDATE product_name = VALUES(product_name), form = VALUES(form), strength = VALUES(strength), source = VALUES(source);